server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sales?useUnicode=true&serverTimezone=GMT%2b8&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    initialSize: 5
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUA
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.demo.domain
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    use-column-label: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# pageHelper分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql